### ISSUE TITLE
Pick a more catchy name!

### ISSUE THREAD

**Issue by TomasTomecek** [TomasTomecek/ab#2]
Suggestions are welcome.

Edit: my ideas:
 * ansibuilder

**Comment by aruiz** [comment]
rackham

**Comment by TomasTomecek** [comment]
Thanks Alberto, that was an interesting read (about Calico Jack).

Unfortunately I don't follow how is this tool related to pirates.

In the end, I decided to stick to the `ab` shortcut and name it `ansible-bender`. I couldn't resist having a project with a reference to my favorite TV show -- Futurama. Now I just need to get a nice logo of Bender bending girders in Ansible way.
